name: qtec_task
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  
  # Flutter packages
  # State Management
  flutter_bloc: ^9.1.0

  # Compareing dart objects
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.3

  # Date and Time formatting
  intl: ^0.20.2

  # Network
  retrofit: ^4.4.2

  # Hooks
  flutter_hooks: ^0.21.2

  # Caching Image
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  floor_generator: ^1.5.0
  json_serializable: ^6.6.1
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true